//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento
    {
        public Atendimento()
        {
            this.Reuniao = new HashSet<Reuniao>();
            this.Reuniao1 = new HashSet<Reuniao>();
        }
    
        public int IdAtendimento { get; set; }
        public int IdCliente { get; set; }
        public int IdUsuario { get; set; }
        public string NomeAtendimento { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> DataAtendimento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Reuniao> Reuniao { get; set; }
        public virtual ICollection<Reuniao> Reuniao1 { get; set; }
    }
}
