//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Atendimento = new HashSet<Atendimento>();
            this.Lote = new HashSet<Lote>();
            this.Pagamento = new HashSet<Pagamento>();
            this.Reuniao = new HashSet<Reuniao>();
            this.Reuniao1 = new HashSet<Reuniao>();
        }
    
        public int IdCliente { get; set; }
        public string NomeCliente { get; set; }
        public string NacionalidadeCliente { get; set; }
        public string EstadoCivil { get; set; }
        public string ProfissaoCliente { get; set; }
        public string RGCliente { get; set; }
        public string CPFCliente { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public int IdEndereco { get; set; }
    
        public virtual ICollection<Atendimento> Atendimento { get; set; }
        public virtual tblLogradouros tblLogradouros { get; set; }
        public virtual ICollection<Lote> Lote { get; set; }
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        public virtual ICollection<Reuniao> Reuniao { get; set; }
        public virtual ICollection<Reuniao> Reuniao1 { get; set; }
    }
}
