//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contatos
    {
        public int IdContato { get; set; }
        public int IdCliente { get; set; }
        public string emailCliente { get; set; }
        public string TelResidCliente { get; set; }
        public string CelCliente { get; set; }
        public string FacebookCliente { get; set; }
        public string InstagramCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
