//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImovelTerceiro
    {
        public int IdImovelTerceiro { get; set; }
        public int Idimovel { get; set; }
        public int IdTipoImovel { get; set; }
        public string AreaTotal { get; set; }
        public string AreaContru { get; set; }
        public string Domitotios { get; set; }
        public string Banheiros { get; set; }
        public string Garagem { get; set; }
        public string TotComodos { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual Imovel Imovel { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual TipoImovel TipoImovel { get; set; }
    }
}
