//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imovel
    {
        public Imovel()
        {
            this.ImovelTerceiro = new HashSet<ImovelTerceiro>();
            this.Loteamento = new HashSet<Loteamento>();
        }
    
        public int IdImovel { get; set; }
        public int IdEndereco { get; set; }
        public int NImovel { get; set; }
        public int TipoImovel { get; set; }
        public string StatusImovel { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual tblLogradouros tblLogradouros { get; set; }
        public virtual TipoImovel TipoImovel1 { get; set; }
        public virtual ICollection<ImovelTerceiro> ImovelTerceiro { get; set; }
        public virtual ICollection<Loteamento> Loteamento { get; set; }
    }
}
