//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loteamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loteamento()
        {
            this.Lote = new HashSet<Lote>();
        }
    
        public int IdLoteamento { get; set; }
        public int IdImovel { get; set; }
        public string NomeLoteamento { get; set; }
        public string nMatricula { get; set; }
        public string nProceRegu { get; set; }
        public string nIncra { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Imovel Imovel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lote> Lote { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
