//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loteamento
    {
        public Loteamento()
        {
            this.Lote = new HashSet<Lote>();
        }
    
        public int IdLoteamento { get; set; }
        public int IdImovel { get; set; }
        public string NomeLoteamento { get; set; }
        public string nMatricula { get; set; }
        public string nProceRegu { get; set; }
        public string nIncra { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Imovel Imovel { get; set; }
        public virtual ICollection<Lote> Lote { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
