//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public int IdLote { get; set; }
        public int IdLoteamento { get; set; }
        public int NLote { get; set; }
        public string Nquadra { get; set; }
        public string Mfrente { get; set; }
        public string Mfundo { get; set; }
        public string MLAtDir { get; set; }
        public string MLatEsc { get; set; }
        public string Confrontante { get; set; }
        public string AreaQuadrada { get; set; }
        public string Matricula { get; set; }
        public string IPTU { get; set; }
        public string Rua { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Loteamento Loteamento { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
