//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negociacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negociacao()
        {
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public int IdNegociacao { get; set; }
        public Nullable<int> IdReuniao { get; set; }
        public Nullable<int> IdTipoNegociacao { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> QteDeParc { get; set; }
        public Nullable<double> ValorTot { get; set; }
        public string Comentario { get; set; }
    
        public virtual Reuniao Reuniao { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual TipoNegociacao TipoNegociacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
