//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negociacao
    {
        public Negociacao()
        {
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public int IdNegociacao { get; set; }
        public Nullable<int> IdReuniao { get; set; }
        public Nullable<int> IdTipoNegociacao { get; set; }
        public int IdTipoPagamento { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> QteDeParc { get; set; }
        public Nullable<double> ValorTot { get; set; }
        public string Comentario { get; set; }
    
        public virtual Reuniao Reuniao { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual TipoNegociacao TipoNegociacao { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
