//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int IdPagamento { get; set; }
        public Nullable<int> IdNegociacao { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> nParcela { get; set; }
        public Nullable<double> Valor { get; set; }
        public int IdTipoPagamento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Negociacao Negociacao { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
    }
}
