//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reuniao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reuniao()
        {
            this.Atendimento = new HashSet<Atendimento>();
            this.Negociacao = new HashSet<Negociacao>();
        }
    
        public int IdReuniao { get; set; }
        public int idCorretor { get; set; }
        public int IdVendedor { get; set; }
        public int idComprador { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdImovel { get; set; }
        public string NomeReuniao { get; set; }
        public Nullable<System.DateTime> DataReuniao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento> Atendimento { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Imovel Imovel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negociacao> Negociacao { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
