//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reuniao
    {
        public Reuniao()
        {
            this.Negociacao = new HashSet<Negociacao>();
        }
    
        public int IdReuniao { get; set; }
        public int IdAtendimento { get; set; }
        public int IdAtendimento2 { get; set; }
        public int IdUsuario { get; set; }
        public int IdCliente { get; set; }
        public int IdCliente2 { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Atendimento Atendimento { get; set; }
        public virtual Atendimento Atendimento1 { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual ICollection<Negociacao> Negociacao { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
