//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftHomeDesenvEntities : DbContext
    {
        public SoftHomeDesenvEntities()
            : base("name=SoftHomeDesenvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Atendimento> Atendimento { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<IdTipoImovel> IdTipoImovel { get; set; }
        public DbSet<Imovel> Imovel { get; set; }
        public DbSet<ImovelTerceiro> ImovelTerceiro { get; set; }
        public DbSet<Lote> Lote { get; set; }
        public DbSet<Loteamento> Loteamento { get; set; }
        public DbSet<Negociacao> Negociacao { get; set; }
        public DbSet<Pagamento> Pagamento { get; set; }
        public DbSet<Reuniao> Reuniao { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tblBairros> tblBairros { get; set; }
        public DbSet<tblCidades> tblCidades { get; set; }
        public DbSet<tblLogradouros> tblLogradouros { get; set; }
        public DbSet<tblStatus> tblStatus { get; set; }
        public DbSet<tblUF> tblUF { get; set; }
        public DbSet<TipoImovel> TipoImovel { get; set; }
        public DbSet<TipoNegociacao> TipoNegociacao { get; set; }
        public DbSet<TipoPagamento> TipoPagamento { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
