//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBairros
    {
        public tblBairros()
        {
            this.tblLogradouros = new HashSet<tblLogradouros>();
        }
    
        public int Codigo { get; set; }
        public string Descricao { get; set; }
        public string BairroAbreviado { get; set; }
        public string UF { get; set; }
        public int CodigoCidade { get; set; }
    
        public virtual tblCidades tblCidades { get; set; }
        public virtual tblUF tblUF { get; set; }
        public virtual ICollection<tblLogradouros> tblLogradouros { get; set; }
    }
}
