//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCidades
    {
        public tblCidades()
        {
            this.tblBairros = new HashSet<tblBairros>();
            this.tblLogradouros = new HashSet<tblLogradouros>();
        }
    
        public int Codigo { get; set; }
        public string Descricao { get; set; }
        public string Descricao_B { get; set; }
        public string CEP { get; set; }
        public string UF { get; set; }
        public int SITUACAO { get; set; }
        public string TIPO_LOCALIDADE { get; set; }
        public Nullable<int> LOC_NU_SEQUENCIAL_SUB { get; set; }
    
        public virtual ICollection<tblBairros> tblBairros { get; set; }
        public virtual tblUF tblUF { get; set; }
        public virtual ICollection<tblLogradouros> tblLogradouros { get; set; }
    }
}
