//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCidades()
        {
            this.tblBairros = new HashSet<tblBairros>();
        }
    
        public int Codigo { get; set; }
        public string Descricao { get; set; }
        public string Descricao_B { get; set; }
        public string CEP { get; set; }
        public string UF { get; set; }
        public int SITUACAO { get; set; }
        public string TIPO_LOCALIDADE { get; set; }
        public Nullable<int> LOC_NU_SEQUENCIAL_SUB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBairros> tblBairros { get; set; }
        public virtual tblUF tblUF { get; set; }
    }
}
