//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogradouros
    {
        public tblLogradouros()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Imovel = new HashSet<Imovel>();
        }
    
        public int Codigo { get; set; }
        public string UF { get; set; }
        public int CodigoCidade { get; set; }
        public string DescricaoNaoAbreviada { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> CodigoBairro { get; set; }
        public string CEP { get; set; }
        public Nullable<int> BAI_NU_SEQUENCIAL_FIM { get; set; }
        public string LOG_COMPLEMENTO { get; set; }
        public string LOG_TIPO_LOGRADOURO { get; set; }
        public string LOG_STATUS_TIPO_LOG { get; set; }
        public string DescricaoSemAcento { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Imovel> Imovel { get; set; }
        public virtual tblBairros tblBairros { get; set; }
        public virtual tblCidades tblCidades { get; set; }
        public virtual tblUF tblUF { get; set; }
    }
}
