//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatus
    {
        public tblStatus()
        {
            this.ImovelTerceiro = new HashSet<ImovelTerceiro>();
            this.Lote = new HashSet<Lote>();
            this.Loteamento = new HashSet<Loteamento>();
            this.Negociacao = new HashSet<Negociacao>();
            this.Pagamento = new HashSet<Pagamento>();
            this.Reuniao = new HashSet<Reuniao>();
        }
    
        public int IdStatus { get; set; }
        public string Tabela { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<ImovelTerceiro> ImovelTerceiro { get; set; }
        public virtual ICollection<Lote> Lote { get; set; }
        public virtual ICollection<Loteamento> Loteamento { get; set; }
        public virtual ICollection<Negociacao> Negociacao { get; set; }
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        public virtual ICollection<Reuniao> Reuniao { get; set; }
    }
}
