//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUF
    {
        public tblUF()
        {
            this.tblBairros = new HashSet<tblBairros>();
            this.tblCidades = new HashSet<tblCidades>();
            this.tblLogradouros = new HashSet<tblLogradouros>();
        }
    
        public string Codigo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<tblBairros> tblBairros { get; set; }
        public virtual ICollection<tblCidades> tblCidades { get; set; }
        public virtual ICollection<tblLogradouros> tblLogradouros { get; set; }
    }
}
