//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPagamento
    {
        public int IdTipoPagamento { get; set; }
        public string Descricao { get; set; }
    
        public virtual Negociacao Negociacao { get; set; }
        public virtual Pagamento Pagamento { get; set; }
    }
}
