//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoImovel
    {
        public TipoImovel()
        {
            this.Imovel = new HashSet<Imovel>();
            this.ImovelTerceiro = new HashSet<ImovelTerceiro>();
        }
    
        public int IdTipoImovel { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Imovel> Imovel { get; set; }
        public virtual ICollection<ImovelTerceiro> ImovelTerceiro { get; set; }
    }
}
