//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Atendimento = new HashSet<Atendimento>();
            this.Reuniao = new HashSet<Reuniao>();
        }
    
        public int IdUsuario { get; set; }
        public string emailUsuario { get; set; }
        public string SenhaUsuario { get; set; }
        public string NomeUsuario { get; set; }
        public string TipoUsuario { get; set; }
        public Nullable<System.DateTime> dataDeCadastro { get; set; }
    
        public virtual ICollection<Atendimento> Atendimento { get; set; }
        public virtual ICollection<Reuniao> Reuniao { get; set; }
    }
}
