//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento
    {
        public int IdAtendimento { get; set; }
        public int IdCliente { get; set; }
        public int IdAtendente { get; set; }
        public string NomeAtendimento { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> DataAtendimento { get; set; }
        public Nullable<int> IdReuniao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Reuniao Reuniao { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
