//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Atendimento = new HashSet<Atendimento>();
            this.Contatos = new HashSet<Contatos>();
            this.ImovelTerceiro = new HashSet<ImovelTerceiro>();
            this.Lote = new HashSet<Lote>();
            this.Pagamento = new HashSet<Pagamento>();
            this.Reuniao = new HashSet<Reuniao>();
            this.Reuniao1 = new HashSet<Reuniao>();
        }
    
        public int IdCliente { get; set; }
        public string NomeCliente { get; set; }
        public string NacionalidadeCliente { get; set; }
        public string EstadoCivil { get; set; }
        public string ProfissaoCliente { get; set; }
        public string RGCliente { get; set; }
        public string CPFCliente { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public int IdEndereco { get; set; }
        public Nullable<int> nCasa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento> Atendimento { get; set; }
        public virtual tblLogradouros tblLogradouros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contatos> Contatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImovelTerceiro> ImovelTerceiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lote> Lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reuniao> Reuniao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reuniao> Reuniao1 { get; set; }
    }
}
