//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImovelTerceiro
    {
        public int IdImovelTerceiro { get; set; }
        public string AreaTotal { get; set; }
        public string AreaContru { get; set; }
        public string Domitotios { get; set; }
        public string Banheiros { get; set; }
        public string Garagem { get; set; }
        public string TotComodos { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdTipoImovelTerceiro { get; set; }
        public Nullable<int> IdImovel { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<double> VlrImovel { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Imovel Imovel { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual TipoImovelTerceiro TipoImovelTerceiro { get; set; }
    }
}
