//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftHomeDesenvEntities : DbContext
    {
        public SoftHomeDesenvEntities()
            : base("name=SoftHomeDesenvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atendimento> Atendimento { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Contatos> Contatos { get; set; }
        public virtual DbSet<Imovel> Imovel { get; set; }
        public virtual DbSet<ImovelTerceiro> ImovelTerceiro { get; set; }
        public virtual DbSet<Lote> Lote { get; set; }
        public virtual DbSet<Loteamento> Loteamento { get; set; }
        public virtual DbSet<Negociacao> Negociacao { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<Reuniao> Reuniao { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBairros> tblBairros { get; set; }
        public virtual DbSet<tblCidades> tblCidades { get; set; }
        public virtual DbSet<tblLogradouros> tblLogradouros { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
        public virtual DbSet<tblUF> tblUF { get; set; }
        public virtual DbSet<TipoImovel> TipoImovel { get; set; }
        public virtual DbSet<TipoImovelTerceiro> TipoImovelTerceiro { get; set; }
        public virtual DbSet<TipoNegociacao> TipoNegociacao { get; set; }
        public virtual DbSet<TipoPagamento> TipoPagamento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
