//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBairros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBairros()
        {
            this.tblLogradouros = new HashSet<tblLogradouros>();
        }
    
        public int Codigo { get; set; }
        public string Descricao { get; set; }
        public string BairroAbreviado { get; set; }
        public string UF { get; set; }
        public int CodigoCidade { get; set; }
    
        public virtual tblCidades tblCidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogradouros> tblLogradouros { get; set; }
    }
}
