//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tcc_Unasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogradouros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLogradouros()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Imovel = new HashSet<Imovel>();
        }
    
        public int Codigo { get; set; }
        public string UF { get; set; }
        public int CodigoCidade { get; set; }
        public string DescricaoNaoAbreviada { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> CodigoBairro { get; set; }
        public string CEP { get; set; }
        public Nullable<int> BAI_NU_SEQUENCIAL_FIM { get; set; }
        public string LOG_COMPLEMENTO { get; set; }
        public string LOG_TIPO_LOGRADOURO { get; set; }
        public string LOG_STATUS_TIPO_LOG { get; set; }
        public string DescricaoSemAcento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imovel> Imovel { get; set; }
        public virtual tblBairros tblBairros { get; set; }
    }
}
